version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm ci --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output/
    steps:
      - checkout
      - install_deps
      - run:
          name: Run lint
          command: |
            npm run test-lint --prefix src/
      - run:
          name: Run unit tests
          command: |
            npm run test-unit --prefix src/
  
  integration-test:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output/
    steps:
      - checkout
      - install_deps
      - run:
          name: Run integration tests
          command:
            npm run test-integration --prefix src/
      - store_test_results:
          path: src/test-output/
  
  e2e-test:
    machine:
      image: circleci/classic:latest
    environment:
      QAW_HEADLESS: true
    steps: 
      - checkout
      - run:
          name: End 2 end tests
          no_output_timeout: 2m
          command: |
            chmod +x scripts/e2e-ci.sh
            ./scripts/e2e-ci.sh



  package:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
          name: Package
          command: |
            cd src && npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz
          destination: simpletodoapp-1.0.0.tgz

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-test:
          requires:
            - ci-build
      - e2e-test:
          requires:
            - integration-test
            - ci-build
      - package:
          requires:
            - e2e-test
          filters:
            branches:
              only:
                - master
