version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm ci --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
  
  package:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
          name: Package
          command: |
            cd src && npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz
          destination: simpletodoapp-1.0.0.tgz

workflows:
  build-and-package:
    jobs:
      - ci-build
      - package:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master



